---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart marzban
  ansible.builtin.systemd:
    name: "{{ marzban_service_name }}"
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
