---
- name: Restart marzban
  community.docker.docker_compose_v2:
    project_src: "{{ marzban_install_dir }}"
    state: present
    recreate: always

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
